apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-db-deployment
  labels:
    app: invoice-db
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-db
  template:
    metadata:
      labels:
        app: invoice-db
    spec:
      containers:
      - name: invoice-mongo
        image: mongo
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: invoice-mongo-pvc