apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoice-mongo-pvc
  namespace: production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs