apiVersion: v1
kind: Service
metadata:
  name: invoice-service
  labels:
    app: invoice
    monitoring-group: node
  namespace: production
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: invoice