apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: "nginx"
  name: drone-ingress
  namespace: drone-system
spec:
  rules:
  - host: drone.devheaven.com
    http:
      paths:
      - backend:
          serviceName: drone-service
          servicePort: 80
        path: /
  tls:
  - hosts:
    - drone.devheaven.com
    secretName: drone-cert