apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-deploy
  namespace: drone-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: drone:drone-deploy
rules:
  - apiGroups: ["apps","extensions"]
    resources: ["deployments"]
    verbs: ["get","list","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: drone:drone-deploy
subjects:
  - kind: ServiceAccount
    name: drone-deploy
    namespace: drone-system
roleRef:
  kind: ClusterRole
  name: drone:drone-deploy
  apiGroup: "rbac.authorization.k8s.io"