apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
  labels:
    app: auth-db
  namespace: production
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: auth-db