apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
  namespace: staging
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend