apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hour-mongo-pvc
  namespace: staging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs