apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
  namespace: staging
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: devheavenci/auth-service
        ports:
        - containerPort: 8080
        env:
        - name: GO_HOST
          value: "0.0.0.0"
        - name: GO_PORT
          value: "8080"
        - name: POSTGRES_HOST
          value: "auth-db-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
                name: auth-db
                key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
                name: auth-db
                key: password
        - name: POSTGRES_DB
          value: "devheaven"