apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth
    monitoring-group: golang
  namespace: staging
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: auth