apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-deployment
  labels:
    app: invoice
  namespace: staging
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: invoice
  template:
    metadata:
      labels:
        app: invoice
    spec:
      containers:
      - name: invoice
        image: devheavenci/invoice-service
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        env:
        - name: NODE_HOST
          value: "0.0.0.0"
        - name: NODE_PORT
          value: "8080"
        - name: MONGO_DB
          value: "devheaven"
        - name: MONGO_URI
          value: "mongodb://invoice-db-service:27017/"
        - name: PROJECT_MANAGEMENT_URI
          value: http://project-management-service/
        - name: TASK_MANAGEMENT_URI
          value: http://task-management-service/
        - name: CLIENT_URI
          value: http://client-service/