apiVersion: v1
kind: Service
metadata:
  name: task-management-service
  labels:
    app: task-management
    monitoring-group: node
  namespace: production
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    app: task-management