apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: kube-system
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: devheavenplatform@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    http01: {}