apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-deployment
  labels:
    app: task-management
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-management
  template:
    metadata:
      labels:
        app: task-management
    spec:
      containers:
      - name: task-management
        image: devheavenci/task-management
        ports:
        - containerPort: 8080
        env:
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
        - name: MONGO_DB
          value: "devheaven"
        - name: MONGO_URI
          value: "mongodb://mongo:27017/"