apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-deployment
  labels:
    app: task-management
  namespace: staging
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: task-management
  template:
    metadata:
      labels:
        app: task-management
    spec:
      containers:
      - name: task-management
        image: devheavenci/task-management-service
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        env:
        - name: NODE_HOST
          value: "0.0.0.0"
        - name: NODE_PORT
          value: "8080"
        - name: MONGO_DB
          value: "devheaven"
        - name: MONGO_URI
          value: "mongodb://task-management-db-service:27017/"
        - name: KAFKA_HOST
          value: "kafka-staging.staging.svc.cluster.local:9092"
        - name: KAFKA_GROUP_ID
          value: "task-management-service"