apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-db-deployment
  labels:
    app: client-db
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-db
  template:
    metadata:
      labels:
        app: client-db
    spec:
      containers:
      - name: client-mongo
        image: mongo
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: client-mongo-pvc