service:
  name: sonarqube
  type: ClusterIP
  externalPort: 9000
  internalPort: 9000
  labels:
  annotations: {}
  # May be used in example for internal load balancing in GCP:
  # cloud.google.com/load-balancer-type: Internal
  # loadBalancerSourceRanges:
  # - 0.0.0.0/0
  # loadBalancerIP: 1.2.3.4
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    name: sonar.devheaven.nl
    # default paths for "/" and "/*" will be added
    # path: /
    # If a different path is defined, that path and {path}/* will be added to the ingress resource
    # path: /sonarqube
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    # kubernetes.io/tls-acme: "true"
    # This property allows for reports up to a certain size to be uploaded to SonarQube
    # nginx.ingress.kubernetes.io/proxy-body-size: "8m"

  # Additional labels for Ingress manifest file
  # labels:
  #  traffic-type: external
  #  traffic-type: internal
  tls:
  # Secrets must be manually created in the namespace.
  - secretName: sonar-general-tls
    hosts:
      - sonar.devheaven.nl