apiVersion: v1
kind: Service
metadata:
  name: project-management-service
  labels:
    app: project-management
    monitoring-group: java
  namespace: production
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: project-management