apiVersion: v1
kind: Service
metadata:
  name: portal-service
  labels:
    app: portal
  namespace: portal
spec:
  type: ClusterIP
  ports:
  - name: portal
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: portal