apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: gateway
  namespace: portal
spec:
  rules:
  - host: portal.devheaven.nl
    http:
      paths:
      - backend:
          serviceName: portal-service
          servicePort: 80
        path: /