apiVersion: apps/v1
kind: Deployment
metadata:
  name: personnel-deployment
  labels:
    app: personnel
  namespace: production
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: personnel
  template:
    metadata:
      labels:
        app: personnel
    spec:
      containers:
      - name: personnel
        image: devheavenci/personnel-service
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        env:
        - name: NODE_HOST
          value: "0.0.0.0"
        - name: NODE_PORT
          value: "8080"
        - name: MONGO_DB
          value: "devheaven"
        - name: MONGO_URI
          value: "mongodb://personnel-db-service:27017/"
        - name: AUTH_URI
          value: "http://auth-service"